///////////////////////////////////////////////////////////
//  Description.cs
//  Implementation of the Class Description
//  Generated by Enterprise Architect
//  Created on:      08-May-2019 2:32:35 PM
//  Original author: Matija
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class Description {

	private int dataset;
	private List<HistoricalProperty> historicalList;
	private int id;


    public Description(int dataset) {
        if (dataset < 0 || dataset > 4)
            throw new ArgumentException("Dataset mora biti u intervalu 1-5.");

        HistoricalList = new List<HistoricalProperty>();
        HistoricalList.Add(new HistoricalProperty(null, null));
        HistoricalList.Add(new HistoricalProperty(null, null));
        this.dataset = dataset;
	}

    public Description()
    {
        HistoricalList = new List<HistoricalProperty>();
        HistoricalList.Add(new HistoricalProperty(null, null));
        HistoricalList.Add(new HistoricalProperty(null, null));
    }

	~Description(){

	}

	public int Dataset{
		get{
			return dataset;
		}
		set{
			dataset = value;
		}
	}

	public List<HistoricalProperty> HistoricalList{
		get{
			return historicalList;
		}
		set{
			historicalList = value;
		}
	}

    public int ID { get => id; set => id = value; }

    public override string ToString()
    {
        string result = "";
        result += $"dataset: {Dataset}\n";

        foreach(var item in HistoricalList)
        {
            result += item.Code;
            result += item.HistoricalValue.IDGeoPolozaja;
            result += item.HistoricalValue.Potrosnja + "\n";
            result += item.HistoricalValue.Timestamp + "\n";
            
        }

        return result;
    }
}//end Description