                                               ///////////////////////////////////////////////////////////
//  HistoricalProperty.cs
//  Implementation of the Class HistoricalProperty
//  Generated by Enterprise Architect
//  Created on:      08-May-2019 2:32:36 PM
//  Original author: Matija
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class HistoricalProperty {

    private int id;
	private string code;
	private Value historicalValue;

	public HistoricalProperty(){

	}

    public HistoricalProperty(string c, Value hv)
    {
        if (c == "")
            throw new ArgumentException("Kod ne sme biti prazan string.");


        this.code = c;
        this.historicalValue = hv;
    }

	~HistoricalProperty(){

	}

	public string Code{
		get{
			return code;
		}
		set{
			code = value;
		}
	}

	public Value HistoricalValue{
		get{
			return historicalValue;
		}
		set{
			historicalValue = value;
		}
	}

    public int Id { get => id; set => id = value; }

    public override string ToString()
    {
        return $"Code: {Code}\n Value: {HistoricalValue}";
    }
}//end HistoricalProperty