///////////////////////////////////////////////////////////
//  CollectionDescription.cs
//  Implementation of the Class CollectionDescription
//  Generated by Enterprise Architect
//  Created on:      08-May-2019 2:32:35 PM
//  Original author: Matija
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class CollectionDescription {

	private DumpingPropertyCollection dpc;
	private int id=0;
    private int dataset;

	public CollectionDescription(){
        dpc = new DumpingPropertyCollection();
	}

    public CollectionDescription(int dataset)
    {
        if (dataset < 0 || dataset > 4)
            throw new ArgumentException("Prosledjena dataset vrednost mora biti u intervalu 1-5");

        this.dataset = dataset;
        this.dpc = new DumpingPropertyCollection();
    }

	~CollectionDescription(){

	}

	public DumpingPropertyCollection Dpc
    {
		get{
			return dpc;
		}
		set{
			dpc = value;
		}
	}

	public int ID{
		get{
			return id;
		}
		set{
			id = value;
		}
	}

    public int Dataset { get => dataset; set => dataset = value; }
}//end CollectionDescription