///////////////////////////////////////////////////////////
//  DeltaCD.cs
//  Implementation of the Class DeltaCD
//  Generated by Enterprise Architect
//  Created on:      08-May-2019 2:32:35 PM
//  Original author: Matija
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class DeltaCD {

    private Dictionary<int, CollectionDescription> addDic = new Dictionary<int, CollectionDescription>();
    private Dictionary<int, CollectionDescription> removeDic= new Dictionary<int, CollectionDescription>();
    private int transactionID=0;
    private Dictionary<int, CollectionDescription> updateDic = new Dictionary<int, CollectionDescription>();

	public DeltaCD(){
        for(int i=0;i<5;i++)
        {
            addDic.Add(i, new CollectionDescription(i));
            removeDic.Add(i, new CollectionDescription(i));
            updateDic.Add(i, new CollectionDescription(i));
            addDic[i].Dataset = i;
            addDic[i].Dpc = new DumpingPropertyCollection();
            removeDic[i].Dataset = i;
            removeDic[i].Dpc = new DumpingPropertyCollection();
            updateDic[i].Dataset = i;
            updateDic[i].Dpc = new DumpingPropertyCollection();
        }
	}

	~DeltaCD(){

	}

    public Dictionary<int, CollectionDescription> AddDic { get => addDic; set => addDic = value; }
    public Dictionary<int, CollectionDescription> RemoveDic { get => removeDic; set => removeDic = value; }
    public Dictionary<int, CollectionDescription> UpdateDic { get => updateDic; set => updateDic = value; }
    public int TransactionID { get => transactionID; set => transactionID = value; }
}//end DeltaCD