///////////////////////////////////////////////////////////
//  DumpingProperty.cs
//  Implementation of the Class DumpingProperty
//  Generated by Enterprise Architect
//  Created on:      08-May-2019 2:32:35 PM
//  Original author: Matija
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class DumpingProperty {

	private string code;
	private Value dumpingValue;

	public DumpingProperty(){

	}

    public DumpingProperty(string c, Value val)
    {
        code = c;
        dumpingValue = val;
    }

    ~DumpingProperty(){

	}

	public string Code{
		get{
			return code;
		}
		set{
			code = value;
		}
	}

	public Value DumpingValue{
		get{
			return dumpingValue;
		}
		set{
			dumpingValue = value;
		}
	}

}//end DumpingProperty