///////////////////////////////////////////////////////////
//  Client.cs
//  Implementation of the Class Client
//  Generated by Enterprise Architect
//  Created on:      08-May-2019 2:32:35 PM
//  Original author: sale
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using System.Threading.Tasks;


public class Client : IClient
{

	public IClient m_IClient;
   
    public Reader reader;

    
    public Writter Writter { get; set; }

    public Reader Reader { get; set; }

    public Client(){
        Writter = new Writter();
        Reader = new Reader();
	}

	~Client(){

	}

    public void ManualWriteToHistory(string code, Value value)
    {
        Task.Run(() =>
        {
            Writter.ManualWriteToHistory(code, value);
        });
        
    }

    public string ReadData(string code, DateTime time) 
    { //ovde treba da se citaju podaci iz readera za prikaz korisniku 
 
        var result = "";

        //result = Reader.ReadData(code, time);

        return result;
    }

    public void WriteToDumpingBuffer(string code, Value value, bool bflag)
    {
        Task.Run(() =>
        {
            Writter.WriteToDumpingBuffer(code, value, bflag);
        });
        //Writter.WriteToDumpingBuffer(code, value);

    
    }

    

   

   
}//end Client