///////////////////////////////////////////////////////////
//  Class1.cs
//  Implementation of the Class Class1
//  Generated by Enterprise Architect
//  Created on:      08-May-2019 2:32:34 PM
//  Original author: Matija
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class Class1 {

	public Class1(){

	}

	~Class1(){

	}

}//end Class1