///////////////////////////////////////////////////////////
//  Client.cs
//  Implementation of the Class Client
//  Generated by Enterprise Architect
//  Created on:      08-May-2019 2:32:35 PM
//  Original author: sale
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class Client {

	public IClient m_IClient;

	public Client(){

	}

	~Client(){

	}

}//end Client