///////////////////////////////////////////////////////////
//  Description.cs
//  Implementation of the Class Description
//  Generated by Enterprise Architect
//  Created on:      08-May-2019 2:32:35 PM
//  Original author: Matija
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class Description {

	private string dataset;
	private List historicalList;
	private int id;
	public List<HistoricalProperty> m_HistoricalProperty;

	public Description(){

	}

	~Description(){

	}

	public string Dataset{
		get{
			return dataset;
		}
		set{
			dataset = value;
		}
	}

	public List HistoricalList{
		get{
			return historicalList;
		}
		set{
			historicalList = value;
		}
	}

}//end Description