///////////////////////////////////////////////////////////
//  DumpingPropertyCollection.cs
//  Implementation of the Class DumpingPropertyCollection
//  Generated by Enterprise Architect
//  Created on:      08-May-2019 2:32:35 PM
//  Original author: Matija
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class DumpingPropertyCollection {

	public List<DumpingProperty> m_DumpingProperty;

	public DumpingPropertyCollection(){

	}

	~DumpingPropertyCollection(){

	}

}//end DumpingPropertyCollection