///////////////////////////////////////////////////////////
//  Historical.cs
//  Implementation of the Class Historical
//  Generated by Enterprise Architect
//  Created on:      08-May-2019 2:32:35 PM
//  Original author: sale
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class Historical {

	public List<Description> m_Description;

	public Historical(){

	}

	~Historical(){

	}

}//end Historical