///////////////////////////////////////////////////////////
//  HistoricalProperty.cs
//  Implementation of the Class HistoricalProperty
//  Generated by Enterprise Architect
//  Created on:      08-May-2019 2:32:36 PM
//  Original author: Matija
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class HistoricalProperty {

	private string code;
	private double historicalValue;

	public HistoricalProperty(){

	}

	~HistoricalProperty(){

	}

	public string Code{
		get{
			return code;
		}
		set{
			code = value;
		}
	}

	public double HistoricalValue{
		get{
			return historicalValue;
		}
		set{
			historicalValue = value;
		}
	}

}//end HistoricalProperty