///////////////////////////////////////////////////////////
//  Reader.cs
//  Implementation of the Class Reader
//  Generated by Enterprise Architect
//  Created on:      08-May-2019 2:32:36 PM
//  Original author: sale
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class Reader : IClient {

	public Historical m_Historical;

	public Reader(){

	}

	~Reader(){

	}

	public void ReadData(){

	}

	/// 
	/// <param name="code"></param>
	/// <param name="value"></param>
	public void ManualWriteToHistory(string code, Value value){

	}

	/// 
	/// <param name="code"></param>
	/// <param name="value"></param>
	public void WriteToDumpingBuffer(string code, Value value){

	}

}//end Reader