///////////////////////////////////////////////////////////
//  IClient.cs
//  Implementation of the Interface IClient
//  Generated by Enterprise Architect
//  Created on:      08-May-2019 2:32:36 PM
//  Original author: Matija
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public interface IClient  {

	/// 
	/// <param name="code"></param>
	/// <param name="value"></param>
	void ManualWriteToHistory(string code, Value value);


	/// 
	/// <param name="code"></param>
	/// <param name="value"></param>
	void WriteToDumpingBuffer(string code, Value value, bool bflag);
}//end IClient